name: Scan Docker Containers

on:
  workflow_run:
    workflows: ["Publish Docker Images"]
    branches:
      - main
      - master
    types: 
      - completed

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: zconger/miniapi
      APP_HOST: http://localhost:5000
      API_KEY: ${{ secrets.SHAWK_API_KEY }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run MiniAPI
        run: docker run --detach --publish 5000:5000 $IMAGE_NAME
#      - name: Run HawkScan
#        run: docker run --tty --volume $(pwd):/hawk --env API_KEY --env APP_HOST --network host stackhawk/hawkscan
      - name: Run HawkScan Action
        uses: stackhawk/hawkscan-action@v1
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
          environmentVariables: APP_HOST, SHAWK_RESULTS_ENDPOINT, SHAWK_AUTH_ENDPOINT
